from typing import Any
from security.models.security_event_schema import SecurityEventSchema
from app.database.supabase_client import supabase

class SecurityEventDeduplicator:
    """Deduplicate events before ingestion"""
    
    def __init__(self, db_client=supabase):
        self.db_client = db_client
        
    def is_duplicate(self, event: SecurityEventSchema) -> bool:
        """
        Check if an event already exists using deterministic fingerprinting.
        The event_id is generated by the normalizer consistently.
        """
        try:
            # Query the raw security_events table. 
            # We check if an event with the same ID and organization_id already exists.
            # Assuming 'event_id' is mapped in the Supabase schema, or we can check raw JSON if not.
            # For this implementation, we assume `event_id` is a column. If it's inside `metadata`, we adjust.
            # We'll use the raw data representation from the schema insertion.
            
            # Note: since the Supabase table stores raw event data directly, 
            # we query where organization_id matches and event_id matches.
            result = self.db_client.table("security_events").select("id").eq("organization_id", event.organization_id).eq("event_id", event.event_id).execute()
            
            return len(result.data) > 0
        except Exception:
            # Fall open - if we can't check, assume it's not duplicate to avoid dropping data?
            # Or assume it is duplicate to avoid spam? Usually fall-open is better for security logging,
            # but for a DB error, we can just return False.
            return False
