"""add_cloud_assets_tables

Revision ID: 8f0ab4b64e3b
Revises: 810b4615d5cd
Create Date: 2026-07-31 21:57:15.439674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f0ab4b64e3b'
down_revision: Union[str, None] = '810b4615d5cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_accounts',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.Enum('AWS', 'AZURE', 'GCP', name='cloudprovider'), nullable=False),
    sa.Column('aws_access_key_id', sa.String(length=100), nullable=True),
    sa.Column('aws_secret_access_key', sa.String(length=100), nullable=True),
    sa.Column('aws_region', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('CONNECTED', 'DISCONNECTED', 'FAILED', name='cloudaccountstatus'), nullable=True),
    sa.Column('last_scan_at', sa.DateTime(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cloud_assets',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.Enum('AWS', 'AZURE', 'GCP', name='cloudprovider'), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['cloud_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cloud_assets_resource_id'), 'cloud_assets', ['resource_id'], unique=False)
    op.create_index(op.f('ix_cloud_assets_type'), 'cloud_assets', ['type'], unique=False)
    op.create_table('ec2_instances',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('instance_id', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('public_ip', sa.String(length=50), nullable=True),
    sa.Column('private_ip', sa.String(length=50), nullable=True),
    sa.Column('instance_type', sa.String(length=50), nullable=False),
    sa.Column('security_groups', sa.JSON(), nullable=True),
    sa.Column('has_public_ip', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['cloud_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id')
    )
    op.create_table('iam_users',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('arn', sa.String(length=300), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('access_keys_age_days', sa.Integer(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['cloud_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id')
    )
    op.create_table('s3_buckets',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('bucket_name', sa.String(length=200), nullable=False),
    sa.Column('arn', sa.String(length=300), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('encryption_enabled', sa.Boolean(), nullable=True),
    sa.Column('versioning_enabled', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['cloud_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id')
    )
    op.create_table('security_groups',
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.String(length=100), nullable=False),
    sa.Column('group_name', sa.String(length=200), nullable=False),
    sa.Column('vpc_id', sa.String(length=100), nullable=True),
    sa.Column('ingress_rules', sa.JSON(), nullable=True),
    sa.Column('egress_rules', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['cloud_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('security_groups')
    op.drop_table('s3_buckets')
    op.drop_table('iam_users')
    op.drop_table('ec2_instances')
    op.drop_index(op.f('ix_cloud_assets_type'), table_name='cloud_assets')
    op.drop_index(op.f('ix_cloud_assets_resource_id'), table_name='cloud_assets')
    op.drop_table('cloud_assets')
    op.drop_table('cloud_accounts')
    # ### end Alembic commands ###
